SOURCES += \
	Rocket/Source/Controls/Clipboard.cpp \
	Rocket/Source/Controls/Controls.cpp \
	Rocket/Source/Controls/DataFormatter.cpp \
	Rocket/Source/Controls/DataQuery.cpp \
	Rocket/Source/Controls/DataSource.cpp \
	Rocket/Source/Controls/DataSourceListener.cpp \
	Rocket/Source/Controls/ElementDataGrid.cpp \
	Rocket/Source/Controls/ElementDataGridCell.cpp \
	Rocket/Source/Controls/ElementDataGridExpandButton.cpp \
	Rocket/Source/Controls/ElementDataGridRow.cpp \
	Rocket/Source/Controls/ElementForm.cpp \
	Rocket/Source/Controls/ElementFormControl.cpp \
	Rocket/Source/Controls/ElementFormControlDataSelect.cpp \
	Rocket/Source/Controls/ElementFormControlInput.cpp \
	Rocket/Source/Controls/ElementFormControlSelect.cpp \
	Rocket/Source/Controls/ElementFormControlTextArea.cpp \
	Rocket/Source/Controls/ElementTabSet.cpp \
	Rocket/Source/Controls/ElementTextSelection.cpp \
	Rocket/Source/Controls/InputType.cpp \
	Rocket/Source/Controls/InputTypeButton.cpp \
	Rocket/Source/Controls/InputTypeCheckbox.cpp \
	Rocket/Source/Controls/InputTypeRadio.cpp \
	Rocket/Source/Controls/InputTypeRange.cpp \
	Rocket/Source/Controls/InputTypeSubmit.cpp \
	Rocket/Source/Controls/InputTypeText.cpp \
	Rocket/Source/Controls/SelectOption.cpp \
	Rocket/Source/Controls/WidgetDropDown.cpp \
	Rocket/Source/Controls/WidgetSlider.cpp \
	Rocket/Source/Controls/WidgetSliderInput.cpp \
	Rocket/Source/Controls/WidgetTextInput.cpp \
	Rocket/Source/Controls/WidgetTextInputMultiLine.cpp \
	Rocket/Source/Controls/WidgetTextInputSingleLine.cpp \
	Rocket/Source/Controls/WidgetTextInputSingleLinePassword.cpp \
	Rocket/Source/Controls/XMLNodeHandlerDataGrid.cpp \
	Rocket/Source/Controls/XMLNodeHandlerTabSet.cpp \
	Rocket/Source/Controls/XMLNodeHandlerTextArea.cpp \
	Rocket/Source/Core/BaseXMLParser.cpp \
	Rocket/Source/Core/Box.cpp \
	Rocket/Source/Core/Clock.cpp \
	Rocket/Source/Core/Context.cpp \
	Rocket/Source/Core/ContextInstancer.cpp \
	Rocket/Source/Core/ContextInstancerDefault.cpp \
	Rocket/Source/Core/ConvolutionFilter.cpp \
	Rocket/Source/Core/Core.cpp \
	Rocket/Source/Core/Decorator.cpp \
	Rocket/Source/Core/DecoratorInstancer.cpp \
	Rocket/Source/Core/DecoratorNone.cpp \
	Rocket/Source/Core/DecoratorNoneInstancer.cpp \
	Rocket/Source/Core/DecoratorTiled.cpp \
	Rocket/Source/Core/DecoratorTiledBox.cpp \
	Rocket/Source/Core/DecoratorTiledBoxInstancer.cpp \
	Rocket/Source/Core/DecoratorTiledHorizontal.cpp \
	Rocket/Source/Core/DecoratorTiledHorizontalInstancer.cpp \
	Rocket/Source/Core/DecoratorTiledImage.cpp \
	Rocket/Source/Core/DecoratorTiledImageInstancer.cpp \
	Rocket/Source/Core/DecoratorTiledInstancer.cpp \
	Rocket/Source/Core/DecoratorTiledVertical.cpp \
	Rocket/Source/Core/DecoratorTiledVerticalInstancer.cpp \
	Rocket/Source/Core/Dictionary.cpp \
	Rocket/Source/Core/DocumentHeader.cpp \
	Rocket/Source/Core/Element.cpp \
	Rocket/Source/Core/ElementBackground.cpp \
	Rocket/Source/Core/ElementBorder.cpp \
	Rocket/Source/Core/ElementDecoration.cpp \
	Rocket/Source/Core/ElementDefinition.cpp \
	Rocket/Source/Core/ElementDocument.cpp \
	Rocket/Source/Core/ElementHandle.cpp \
	Rocket/Source/Core/ElementImage.cpp \
	Rocket/Source/Core/ElementInstancer.cpp \
	Rocket/Source/Core/ElementReference.cpp \
	Rocket/Source/Core/ElementScroll.cpp \
	Rocket/Source/Core/ElementStyle.cpp \
	Rocket/Source/Core/ElementText.cpp \
	Rocket/Source/Core/ElementTextDefault.cpp \
	Rocket/Source/Core/ElementUtilities.cpp \
	Rocket/Source/Core/Event.cpp \
	Rocket/Source/Core/EventDispatcher.cpp \
	Rocket/Source/Core/EventInstancer.cpp \
	Rocket/Source/Core/EventInstancerDefault.cpp \
	Rocket/Source/Core/EventListenerInstancer.cpp \
	Rocket/Source/Core/Factory.cpp \
	Rocket/Source/Core/FileInterface.cpp \
	Rocket/Source/Core/FileInterfaceDefault.cpp \
	Rocket/Source/Core/FontDatabase.cpp \
	Rocket/Source/Core/FontEffect.cpp \
	Rocket/Source/Core/FontEffectInstancer.cpp \
	Rocket/Source/Core/FontEffectNone.cpp \
	Rocket/Source/Core/FontEffectNoneInstancer.cpp \
	Rocket/Source/Core/FontEffectOutline.cpp \
	Rocket/Source/Core/FontEffectOutlineInstancer.cpp \
	Rocket/Source/Core/FontEffectShadow.cpp \
	Rocket/Source/Core/FontEffectShadowInstancer.cpp \
	Rocket/Source/Core/FontFace.cpp \
	Rocket/Source/Core/FontFaceHandle.cpp \
	Rocket/Source/Core/FontFaceLayer.cpp \
	Rocket/Source/Core/FontFamily.cpp \
	Rocket/Source/Core/Geometry.cpp \
	Rocket/Source/Core/GeometryDatabase.cpp \
	Rocket/Source/Core/GeometryUtilities.cpp \
	Rocket/Source/Core/LayoutBlockBox.cpp \
	Rocket/Source/Core/LayoutBlockBoxSpace.cpp \
	Rocket/Source/Core/LayoutEngine.cpp \
	Rocket/Source/Core/LayoutInlineBox.cpp \
	Rocket/Source/Core/LayoutInlineBoxText.cpp \
	Rocket/Source/Core/LayoutLineBox.cpp \
	Rocket/Source/Core/Log.cpp \
	Rocket/Source/Core/Math.cpp \
	Rocket/Source/Core/Plugin.cpp \
	Rocket/Source/Core/PluginRegistry.cpp \
	Rocket/Source/Core/precompiled.cpp \
	Rocket/Source/Core/Property.cpp \
	Rocket/Source/Core/PropertyDefinition.cpp \
	Rocket/Source/Core/PropertyDictionary.cpp \
	Rocket/Source/Core/PropertyParserColour.cpp \
	Rocket/Source/Core/PropertyParserKeyword.cpp \
	Rocket/Source/Core/PropertyParserNumber.cpp \
	Rocket/Source/Core/PropertyParserString.cpp \
	Rocket/Source/Core/PropertySpecification.cpp \
	Rocket/Source/Core/ReferenceCountable.cpp \
	Rocket/Source/Core/RenderInterface.cpp \
	Rocket/Source/Core/RocketStream.cpp \
	Rocket/Source/Core/StreamFile.cpp \
	Rocket/Source/Core/StreamMemory.cpp \
	Rocket/Source/Core/String.cpp \
	Rocket/Source/Core/StringCache.cpp \
	Rocket/Source/Core/StringUtilities.cpp \
	Rocket/Source/Core/StyleSheet.cpp \
	Rocket/Source/Core/StyleSheetFactory.cpp \
	Rocket/Source/Core/StyleSheetNode.cpp \
	Rocket/Source/Core/StyleSheetNodeSelector.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorEmpty.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorFirstChild.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorFirstOfType.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorLastChild.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorLastOfType.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorNthChild.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorNthLastChild.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorNthLastOfType.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorNthOfType.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorOnlyChild.cpp \
	Rocket/Source/Core/StyleSheetNodeSelectorOnlyOfType.cpp \
	Rocket/Source/Core/StyleSheetParser.cpp \
	Rocket/Source/Core/StyleSheetSpecification.cpp \
	Rocket/Source/Core/SystemInterface.cpp \
	Rocket/Source/Core/Template.cpp \
	Rocket/Source/Core/TemplateCache.cpp \
	Rocket/Source/Core/Texture.cpp \
	Rocket/Source/Core/TextureDatabase.cpp \
	Rocket/Source/Core/TextureLayout.cpp \
	Rocket/Source/Core/TextureLayoutRectangle.cpp \
	Rocket/Source/Core/TextureLayoutRow.cpp \
	Rocket/Source/Core/TextureLayoutTexture.cpp \
	Rocket/Source/Core/TextureResource.cpp \
	Rocket/Source/Core/UnicodeRange.cpp \
	Rocket/Source/Core/URL.cpp \
	Rocket/Source/Core/Variant.cpp \
	Rocket/Source/Core/Vector2.cpp \
	Rocket/Source/Core/RocketWidgetSlider.cpp \
	Rocket/Source/Core/WidgetSliderScroll.cpp \
	Rocket/Source/Core/WString.cpp \
	Rocket/Source/Core/XMLNodeHandler.cpp \
	Rocket/Source/Core/XMLNodeHandlerBody.cpp \
	Rocket/Source/Core/XMLNodeHandlerDefault.cpp \
	Rocket/Source/Core/XMLNodeHandlerHead.cpp \
	Rocket/Source/Core/XMLNodeHandlerTemplate.cpp \
	Rocket/Source/Core/XMLParser.cpp \
	Rocket/Source/Core/XMLParseTools.cpp \
	Rocket/Source/Debugger/Debugger.cpp \
	Rocket/Source/Debugger/ElementContextHook.cpp \
	Rocket/Source/Debugger/ElementInfo.cpp \
	Rocket/Source/Debugger/ElementLog.cpp \
	Rocket/Source/Debugger/DebugGeometry.cpp \
	Rocket/Source/Debugger/DebugPlugin.cpp \
	Rocket/Source/Debugger/DebugSystemInterface.cpp
	
HEADERS += \
	Rocket/Controls/Clipboard.h \
	Rocket/Controls/Controls.h \
	Rocket/Controls/DataFormatter.h \
	Rocket/Controls/DataQuery.h \
	Rocket/Controls/DataSource.h \
	Rocket/Controls/DataSourceListener.h \
	Rocket/Controls/ElementDataGrid.h \
	Rocket/Controls/ElementDataGridCell.h \
	Rocket/Controls/ElementDataGridExpandButton.h \
	Rocket/Controls/ElementDataGridRow.h \
	Rocket/Controls/ElementForm.h \
	Rocket/Controls/ElementFormControl.h \
	Rocket/Controls/ElementFormControlDataSelect.h \
	Rocket/Controls/ElementFormControlInput.h \
	Rocket/Controls/ElementFormControlSelect.h \
	Rocket/Controls/ElementFormControlTextArea.h \
	Rocket/Controls/ElementTabSet.h \
	Rocket/Controls/Header.h \
	Rocket/Controls/SelectOption.h \
	Rocket/Controls.h \
	Rocket/Core/BaseXMLParser.h \
	Rocket/Core/Box.h \
	Rocket/Core/Colour.h \
	Rocket/Core/Context.h \
	Rocket/Core/ContextInstancer.h \
	Rocket/Core/ConvolutionFilter.h \
	Rocket/Core/Core.h \
	Rocket/Core/Debug.h \
	Rocket/Core/Decorator.h \
	Rocket/Core/DecoratorInstancer.h \
	Rocket/Core/Dictionary.h \
	Rocket/Core/Element.h \
	Rocket/Core/ElementDocument.h \
	Rocket/Core/ElementInstancer.h \
	Rocket/Core/ElementInstancerGeneric.h \
	Rocket/Core/ElementReference.h \
	Rocket/Core/ElementScroll.h \
	Rocket/Core/ElementText.h \
	Rocket/Core/ElementUtilities.h \
	Rocket/Core/Event.h \
	Rocket/Core/EventInstancer.h \
	Rocket/Core/EventListener.h \
	Rocket/Core/EventListenerInstancer.h \
	Rocket/Core/Factory.h \
	Rocket/Core/FileInterface.h \
	Rocket/Core/Font.h \
	Rocket/Core/FontDatabase.h \
	Rocket/Core/FontEffect.h \
	Rocket/Core/FontEffectInstancer.h \
	Rocket/Core/FontGlyph.h \
	Rocket/Core/Geometry.h \
	Rocket/Core/GeometryUtilities.h \
	Rocket/Core/Header.h \
	Rocket/Core/Input.h \
	Rocket/Core/Log.h \
	Rocket/Core/Math.h \
	Rocket/Core/MathTypes.h \
	Rocket/Core/Platform.h \
	Rocket/Core/Plugin.h \
	Rocket/Core/Property.h \
	Rocket/Core/PropertyDefinition.h \
	Rocket/Core/PropertyDictionary.h \
	Rocket/Core/PropertyParser.h \
	Rocket/Core/PropertySpecification.h \
	Rocket/Core/ReferenceCountable.h \
	Rocket/Core/RenderInterface.h \
	Rocket/Core/ScriptInterface.h \
	Rocket/Core/Stream.h \
	Rocket/Core/StreamMemory.h \
	Rocket/Core/String.h \
	Rocket/Core/StringBase.h \
	Rocket/Core/StringUtilities.h \
	Rocket/Core/StyleSheet.h \
	Rocket/Core/StyleSheetKeywords.h \
	Rocket/Core/StyleSheetSpecification.h \
	Rocket/Core/SystemInterface.h \
	Rocket/Core/Texture.h \
	Rocket/Core/TypeConverter.h \
	Rocket/Core/Types.h \
	Rocket/Core/URL.h \
	Rocket/Core/Variant.h \
	Rocket/Core/Vector2.h \
	Rocket/Core/Vertex.h \
	Rocket/Core/WString.h \
	Rocket/Core/XMLNodeHandler.h \
	Rocket/Core/XMLParser.h \
	Rocket/Core.h \
	Rocket/Debugger/Debugger.h \
	Rocket/Debugger/Header.h \
	Rocket/Debugger.h \
	Rocket/Source/Controls/ElementTextSelection.h \
	Rocket/Source/Controls/InputType.h \
	Rocket/Source/Controls/InputTypeButton.h \
	Rocket/Source/Controls/InputTypeCheckbox.h \
	Rocket/Source/Controls/InputTypeRadio.h \
	Rocket/Source/Controls/InputTypeRange.h \
	Rocket/Source/Controls/InputTypeSubmit.h \
	Rocket/Source/Controls/InputTypeText.h \
	Rocket/Source/Controls/WidgetDropDown.h \
	Rocket/Source/Controls/WidgetSlider.h \
	Rocket/Source/Controls/WidgetSliderInput.h \
	Rocket/Source/Controls/WidgetTextInput.h \
	Rocket/Source/Controls/WidgetTextInputMultiLine.h \
	Rocket/Source/Controls/WidgetTextInputSingleLine.h \
	Rocket/Source/Controls/WidgetTextInputSingleLinePassword.h \
	Rocket/Source/Controls/XMLNodeHandlerDataGrid.h \
	Rocket/Source/Controls/XMLNodeHandlerTabSet.h \
	Rocket/Source/Controls/XMLNodeHandlerTextArea.h \
	Rocket/Source/Core/Clock.h \
	Rocket/Source/Core/ContextInstancerDefault.h \
	Rocket/Source/Core/DebugFont.h \
	Rocket/Source/Core/DecoratorNone.h \
	Rocket/Source/Core/DecoratorNoneInstancer.h \
	Rocket/Source/Core/DecoratorTiled.h \
	Rocket/Source/Core/DecoratorTiledBox.h \
	Rocket/Source/Core/DecoratorTiledBoxInstancer.h \
	Rocket/Source/Core/DecoratorTiledHorizontal.h \
	Rocket/Source/Core/DecoratorTiledHorizontalInstancer.h \
	Rocket/Source/Core/DecoratorTiledImage.h \
	Rocket/Source/Core/DecoratorTiledImageInstancer.h \
	Rocket/Source/Core/DecoratorTiledInstancer.h \
	Rocket/Source/Core/DecoratorTiledVertical.h \
	Rocket/Source/Core/DecoratorTiledVerticalInstancer.h \
	Rocket/Source/Core/DocumentHeader.h \
	Rocket/Source/Core/ElementBackground.h \
	Rocket/Source/Core/ElementBorder.h \
	Rocket/Source/Core/ElementDecoration.h \
	Rocket/Source/Core/ElementDefinition.h \
	Rocket/Source/Core/ElementHandle.h \
	Rocket/Source/Core/ElementImage.h \
	Rocket/Source/Core/ElementStyle.h \
	Rocket/Source/Core/ElementTextDefault.h \
	Rocket/Source/Core/EventDispatcher.h \
	Rocket/Source/Core/EventInstancerDefault.h \
	Rocket/Source/Core/EventIterators.h \
	Rocket/Source/Core/FileInterfaceDefault.h \
	Rocket/Source/Core/FontEffectNone.h \
	Rocket/Source/Core/FontEffectNoneInstancer.h \
	Rocket/Source/Core/FontEffectOutline.h \
	Rocket/Source/Core/FontEffectOutlineInstancer.h \
	Rocket/Source/Core/FontEffectShadow.h \
	Rocket/Source/Core/FontEffectShadowInstancer.h \
	Rocket/Source/Core/FontFace.h \
	Rocket/Source/Core/FontFaceHandle.h \
	Rocket/Source/Core/FontFaceLayer.h \
	Rocket/Source/Core/FontFamily.h \
	Rocket/Source/Core/GeometryDatabase.h \
	Rocket/Source/Core/LayoutBlockBox.h \
	Rocket/Source/Core/LayoutBlockBoxSpace.h \
	Rocket/Source/Core/LayoutEngine.h \
	Rocket/Source/Core/LayoutInlineBox.h \
	Rocket/Source/Core/LayoutInlineBoxText.h \
	Rocket/Source/Core/LayoutLineBox.h \
	Rocket/Source/Core/PluginRegistry.h \
	Rocket/Source/Core/Pool.h \
	Rocket/Source/Core/precompiled.h \
	Rocket/Source/Core/PropertyParserColour.h \
	Rocket/Source/Core/PropertyParserKeyword.h \
	Rocket/Source/Core/PropertyParserNumber.h \
	Rocket/Source/Core/PropertyParserString.h \
	Rocket/Source/Core/PropertyShorthandDefinition.h \
	Rocket/Source/Core/StreamFile.h \
	Rocket/Source/Core/StringCache.h \
	Rocket/Source/Core/StyleSheetFactory.h \
	Rocket/Source/Core/StyleSheetNode.h \
	Rocket/Source/Core/StyleSheetNodeSelector.h \
	Rocket/Source/Core/StyleSheetNodeSelectorEmpty.h \
	Rocket/Source/Core/StyleSheetNodeSelectorFirstChild.h \
	Rocket/Source/Core/StyleSheetNodeSelectorFirstOfType.h \
	Rocket/Source/Core/StyleSheetNodeSelectorLastChild.h \
	Rocket/Source/Core/StyleSheetNodeSelectorLastOfType.h \
	Rocket/Source/Core/StyleSheetNodeSelectorNthChild.h \
	Rocket/Source/Core/StyleSheetNodeSelectorNthLastChild.h \
	Rocket/Source/Core/StyleSheetNodeSelectorNthLastOfType.h \
	Rocket/Source/Core/StyleSheetNodeSelectorNthOfType.h \
	Rocket/Source/Core/StyleSheetNodeSelectorOnlyChild.h \
	Rocket/Source/Core/StyleSheetNodeSelectorOnlyOfType.h \
	Rocket/Source/Core/StyleSheetParser.h \
	Rocket/Source/Core/Template.h \
	Rocket/Source/Core/TemplateCache.h \
	Rocket/Source/Core/TextureDatabase.h \
	Rocket/Source/Core/TextureLayout.h \
	Rocket/Source/Core/TextureLayoutRectangle.h \
	Rocket/Source/Core/TextureLayoutRow.h \
	Rocket/Source/Core/TextureLayoutTexture.h \
	Rocket/Source/Core/TextureResource.h \
	Rocket/Source/Core/UnicodeRange.h \
	Rocket/Source/Core/WidgetSlider.h \
	Rocket/Source/Core/WidgetSliderScroll.h \
	Rocket/Source/Core/XMLNodeHandlerBody.h \
	Rocket/Source/Core/XMLNodeHandlerDefault.h \
	Rocket/Source/Core/XMLNodeHandlerHead.h \
	Rocket/Source/Core/XMLNodeHandlerTemplate.h \
	Rocket/Source/Core/XMLParseTools.h \
	Rocket/Source/Debugger/BeaconSource.h \
	Rocket/Source/Debugger/CommonSource.h \
	Rocket/Source/Debugger/ElementContextHook.h \
	Rocket/Source/Debugger/ElementInfo.h \
	Rocket/Source/Debugger/ElementLog.h \
	Rocket/Source/Debugger/FontSource.h \
	Rocket/Source/Debugger/Geometry.h \
	Rocket/Source/Debugger/InfoSource.h \
	Rocket/Source/Debugger/LogSource.h \
	Rocket/Source/Debugger/MenuSource.h \
	Rocket/Source/Debugger/Plugin.h \
	Rocket/Source/Debugger/SystemInterface.h \
	Rocket/Core/Colour.inl \
	Rocket/Core/Dictionary.inl \
	Rocket/Core/Element.inl \
	Rocket/Core/ElementInstancerGeneric.inl \
	Rocket/Core/Pool.inl \
	Rocket/Core/StringBase.inl \
	Rocket/Core/TypeConverter.inl \
	Rocket/Core/Variant.inl \
	Rocket/Core/Vector2.inl \
	Rocket/Source/Core/Pool.inl
